// GENERATED by scripts/gen-icons.py from design-reference/grand-teint/icons — DO NOT EDIT BY HAND.
// WO-5.1 — the 26 Grand Teint glyphs as inline SVG strings (PWA, zero deps).
// currentColor is driven by the element's CSS `color`; size is a parameter.

export const grandTeintIcon = {
  alerte: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M12 4L21 19.5H3L12 4z" /><path xmlns="http://www.w3.org/2000/svg" d="M12 10v4" /><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="16.8" r="1.2" fill="currentColor" stroke="none" /></svg>`,
  argent: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="12" r="8.5" /><path xmlns="http://www.w3.org/2000/svg" d="M10 16V8.5h4.5" /><path xmlns="http://www.w3.org/2000/svg" d="M10 12.2h3.5" /></svg>`,
  cadenas: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect xmlns="http://www.w3.org/2000/svg" x="5.5" y="10.5" width="13" height="9.5" rx="2.5" /><path xmlns="http://www.w3.org/2000/svg" d="M8.5 10.5V8a3.5 3.5 0 0 1 7 0v2.5" /><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="15.2" r="1.4" fill="currentColor" stroke="none" /></svg>`,
  camera: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M4 8h3l2-2.5h6L17 8h3v11H4V8z" /><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="13" r="3.2" /></svg>`,
  chevron: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M9.5 6l6 6-6 6" /></svg>`,
  cle: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle xmlns="http://www.w3.org/2000/svg" cx="8" cy="12" r="3.5" /><path xmlns="http://www.w3.org/2000/svg" d="M11.5 12H20" /><path xmlns="http://www.w3.org/2000/svg" d="M17 12v3" /><path xmlns="http://www.w3.org/2000/svg" d="M20 12v2.2" /></svg>`,
  coche: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M5 12.5l4.5 4.5L19 7.5" /></svg>`,
  colis: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M12 3l7.5 4.2v9.6L12 21l-7.5-4.2V7.2L12 3z" /><path xmlns="http://www.w3.org/2000/svg" d="M4.5 7.2L12 11.5l7.5-4.3" /><path xmlns="http://www.w3.org/2000/svg" d="M12 11.5V21" /></svg>`,
  ecouter: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="12" r="9" /><path xmlns="http://www.w3.org/2000/svg" d="M10.2 8.8l5.2 3.2-5.2 3.2z" fill="currentColor" stroke="none" /></svg>`,
  enregistrer: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="12" r="8.5" /><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="12" r="3.2" fill="currentColor" stroke="none" /></svg>`,
  filtre: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M4 5h16l-6 7v5.5l-4 2.5v-8L4 5z" /></svg>`,
  gains: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M4 17l5-5 3 3 7.5-7.5" /><path xmlns="http://www.w3.org/2000/svg" d="M14.5 7.5h5v5" /></svg>`,
  horloge: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="12" r="9" /><path xmlns="http://www.w3.org/2000/svg" d="M12 7v5l3.5 2" /></svg>`,
  horsligne: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M3 6.5a13 13 0 0 1 18 0" /><path xmlns="http://www.w3.org/2000/svg" d="M6.5 10a8.5 8.5 0 0 1 11 0" /><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="16.5" r="1.6" fill="currentColor" stroke="none" /><path xmlns="http://www.w3.org/2000/svg" d="M4 20L20 4" /></svg>`,
  moto: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle xmlns="http://www.w3.org/2000/svg" cx="5.5" cy="17.5" r="2.4" /><circle xmlns="http://www.w3.org/2000/svg" cx="18.5" cy="17.5" r="2.4" /><path xmlns="http://www.w3.org/2000/svg" d="M7.9 17.5h5.6l2.2-6h3.4" /><path xmlns="http://www.w3.org/2000/svg" d="M15.8 6.8h2.4l1.4 4.7" /><path xmlns="http://www.w3.org/2000/svg" d="M11 11.5H7.2c-1.8 0-3 1.3-3.4 3" /></svg>`,
  oeil: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6z" /><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="12" r="2.6" /></svg>`,
  partager: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle xmlns="http://www.w3.org/2000/svg" cx="6" cy="12" r="2.6" /><circle xmlns="http://www.w3.org/2000/svg" cx="17.5" cy="5.5" r="2.6" /><circle xmlns="http://www.w3.org/2000/svg" cx="17.5" cy="18.5" r="2.6" /><path xmlns="http://www.w3.org/2000/svg" d="M8.4 10.8l6.8-4" /><path xmlns="http://www.w3.org/2000/svg" d="M8.4 13.2l6.8 4" /></svg>`,
  recherche: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle xmlns="http://www.w3.org/2000/svg" cx="11" cy="11" r="6.5" /><path xmlns="http://www.w3.org/2000/svg" d="M16 16l4.5 4.5" /></svg>`,
  refus: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M6.5 6.5l11 11" /><path xmlns="http://www.w3.org/2000/svg" d="M17.5 6.5l-11 11" /></svg>`,
  repere: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M6 21V4" /><path xmlns="http://www.w3.org/2000/svg" d="M6 5h11l-2.5 3.5L17 12H6" /></svg>`,
  reprendre: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M4 10a8 8 0 1 1 2 5.3" /><path xmlns="http://www.w3.org/2000/svg" d="M4 5.5V10h4.5" /></svg>`,
  scelle: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="9.5" r="4.5" /><path xmlns="http://www.w3.org/2000/svg" d="M9.8 13.5L8.5 20.5l3.5-1.8 3.5 1.8-1.3-7" /></svg>`,
  sos: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M12 3.2l6.8 2.7v5.1c0 4.3-2.9 7.2-6.8 8.8-3.9-1.6-6.8-4.5-6.8-8.8V5.9L12 3.2z" /><path xmlns="http://www.w3.org/2000/svg" d="M12 8v4.5" /><circle xmlns="http://www.w3.org/2000/svg" cx="12" cy="15.5" r="1.2" fill="currentColor" stroke="none" /></svg>`,
  telephone: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M5 4h4l1.5 4.5-2.2 1.6a13 13 0 0 0 5.6 5.6l1.6-2.2L20 15v4a1.8 1.8 0 0 1-2 1.8A16.5 16.5 0 0 1 3.2 6 1.8 1.8 0 0 1 5 4z" /></svg>`,
  voix: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path xmlns="http://www.w3.org/2000/svg" d="M12 3a3 3 0 0 1 3 3v5a3 3 0 0 1-6 0V6a3 3 0 0 1 3-3z" /><path xmlns="http://www.w3.org/2000/svg" d="M6 11a6 6 0 0 0 12 0" /><path xmlns="http://www.w3.org/2000/svg" d="M12 17v3.5" /></svg>`,
  zone: (size = 20) =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect xmlns="http://www.w3.org/2000/svg" x="4" y="4" width="7" height="9" /><rect xmlns="http://www.w3.org/2000/svg" x="13.5" y="4" width="6.5" height="5.5" /><rect xmlns="http://www.w3.org/2000/svg" x="13.5" y="12" width="6.5" height="8" /><rect xmlns="http://www.w3.org/2000/svg" x="4" y="15.5" width="7" height="4.5" /></svg>`,
} as const;

export type GrandTeintIconName = keyof typeof grandTeintIcon;
export const GRAND_TEINT_ICON_NAMES = Object.keys(grandTeintIcon) as GrandTeintIconName[];
