// GENERATED by scripts/gen-icons.py from design-reference/grand-teint/icons — DO NOT EDIT BY HAND.
// WO-5.1 — the 29 Grand Teint glyphs as react-native-svg components. currentColor
// resolves against the `color` prop; default 20 dp (legible at the design's icon size).
import { Svg, Path, Circle, Rect } from 'react-native-svg';

export interface IconProps {
  /** dp; the design draws the set on a 24-unit grid, shown at 20 dp. */
  size?: number;
  /** any theme ink token; drives every stroke/fill via currentColor. */
  color?: string;
}

export function IconAccueil({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M4 11l8-7 8 7" />
      <Path d="M6 9.5V20h12V9.5" />
      <Path d="M10 20v-6h4v6" />
    </Svg>
  );
}

export function IconAlerte({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M12 4L21 19.5H3L12 4z" />
      <Path d="M12 10v4" />
      <Circle cx={12} cy={16.8} r={1.2} fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconArgent({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Circle cx={12} cy={12} r={8.5} />
      <Path d="M10 16V8.5h4.5" />
      <Path d="M10 12.2h3.5" />
    </Svg>
  );
}

export function IconCadenas({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Rect x={5.5} y={10.5} width={13} height={9.5} rx={2.5} />
      <Path d="M8.5 10.5V8a3.5 3.5 0 0 1 7 0v2.5" />
      <Circle cx={12} cy={15.2} r={1.4} fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconCamera({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M4 8h3l2-2.5h6L17 8h3v11H4V8z" />
      <Circle cx={12} cy={13} r={3.2} />
    </Svg>
  );
}

export function IconChevron({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M9.5 6l6 6-6 6" />
    </Svg>
  );
}

export function IconCle({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Circle cx={8} cy={12} r={3.5} />
      <Path d="M11.5 12H20" />
      <Path d="M17 12v3" />
      <Path d="M20 12v2.2" />
    </Svg>
  );
}

export function IconCoche({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M5 12.5l4.5 4.5L19 7.5" />
    </Svg>
  );
}

export function IconColis({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M12 3l7.5 4.2v9.6L12 21l-7.5-4.2V7.2L12 3z" />
      <Path d="M4.5 7.2L12 11.5l7.5-4.3" />
      <Path d="M12 11.5V21" />
    </Svg>
  );
}

export function IconEcouter({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Circle cx={12} cy={12} r={9} />
      <Path d="M10.2 8.8l5.2 3.2-5.2 3.2z" fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconEnregistrer({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Circle cx={12} cy={12} r={8.5} />
      <Circle cx={12} cy={12} r={3.2} fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconFiltre({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M4 5h16l-6 7v5.5l-4 2.5v-8L4 5z" />
    </Svg>
  );
}

export function IconGains({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M4 17l5-5 3 3 7.5-7.5" />
      <Path d="M14.5 7.5h5v5" />
    </Svg>
  );
}

export function IconHorloge({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Circle cx={12} cy={12} r={9} />
      <Path d="M12 7v5l3.5 2" />
    </Svg>
  );
}

export function IconHorsligne({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M3 6.5a13 13 0 0 1 18 0" />
      <Path d="M6.5 10a8.5 8.5 0 0 1 11 0" />
      <Circle cx={12} cy={16.5} r={1.6} fill="currentColor" stroke="none" />
      <Path d="M4 20L20 4" />
    </Svg>
  );
}

export function IconMoto({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Circle cx={5.5} cy={17.5} r={2.4} />
      <Circle cx={18.5} cy={17.5} r={2.4} />
      <Path d="M7.9 17.5h5.6l2.2-6h3.4" />
      <Path d="M15.8 6.8h2.4l1.4 4.7" />
      <Path d="M11 11.5H7.2c-1.8 0-3 1.3-3.4 3" />
    </Svg>
  );
}

export function IconOeil({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6z" />
      <Circle cx={12} cy={12} r={2.6} />
    </Svg>
  );
}

export function IconPartager({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Circle cx={6} cy={12} r={2.6} />
      <Circle cx={17.5} cy={5.5} r={2.6} />
      <Circle cx={17.5} cy={18.5} r={2.6} />
      <Path d="M8.4 10.8l6.8-4" />
      <Path d="M8.4 13.2l6.8 4" />
    </Svg>
  );
}

export function IconProduits({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M12 3l7.5 4.2v9.6L12 21l-7.5-4.2V7.2L12 3z" />
      <Path d="M4.5 7.2L12 11.5l7.5-4.3" />
      <Path d="M12 11.5V21" />
    </Svg>
  );
}

export function IconRecherche({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Circle cx={11} cy={11} r={6.5} />
      <Path d="M16 16l4.5 4.5" />
    </Svg>
  );
}

export function IconRefus({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M6.5 6.5l11 11" />
      <Path d="M17.5 6.5l-11 11" />
    </Svg>
  );
}

export function IconRepere({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M6 21V4" />
      <Path d="M6 5h11l-2.5 3.5L17 12H6" />
    </Svg>
  );
}

export function IconReprendre({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M4 10a8 8 0 1 1 2 5.3" />
      <Path d="M4 5.5V10h4.5" />
    </Svg>
  );
}

export function IconScelle({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Circle cx={12} cy={9.5} r={4.5} />
      <Path d="M9.8 13.5L8.5 20.5l3.5-1.8 3.5 1.8-1.3-7" />
    </Svg>
  );
}

export function IconSos({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M12 3.2l6.8 2.7v5.1c0 4.3-2.9 7.2-6.8 8.8-3.9-1.6-6.8-4.5-6.8-8.8V5.9L12 3.2z" />
      <Path d="M12 8v4.5" />
      <Circle cx={12} cy={15.5} r={1.2} fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconTelephone({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M5 4h4l1.5 4.5-2.2 1.6a13 13 0 0 0 5.6 5.6l1.6-2.2L20 15v4a1.8 1.8 0 0 1-2 1.8A16.5 16.5 0 0 1 3.2 6 1.8 1.8 0 0 1 5 4z" />
    </Svg>
  );
}

export function IconVitrine({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M4 9l1.5-4.5h13L20 9" />
      <Path d="M4 9h16v11H4V9z" />
      <Path d="M9.5 20v-6h5v6" />
    </Svg>
  );
}

export function IconVoix({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Path d="M12 3a3 3 0 0 1 3 3v5a3 3 0 0 1-6 0V6a3 3 0 0 1 3-3z" />
      <Path d="M6 11a6 6 0 0 0 12 0" />
      <Path d="M12 17v3.5" />
    </Svg>
  );
}

export function IconZone({ size = 20, color = 'currentColor' }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round"
      color={color} accessibilityRole="image">
      <Rect x={4} y={4} width={7} height={9} />
      <Rect x={13.5} y={4} width={6.5} height={5.5} />
      <Rect x={13.5} y={12} width={6.5} height={8} />
      <Rect x={4} y={15.5} width={7} height={4.5} />
    </Svg>
  );
}

export const GRAND_TEINT_ICONS = [
  'accueil',
  'alerte',
  'argent',
  'cadenas',
  'camera',
  'chevron',
  'cle',
  'coche',
  'colis',
  'ecouter',
  'enregistrer',
  'filtre',
  'gains',
  'horloge',
  'horsligne',
  'moto',
  'oeil',
  'partager',
  'produits',
  'recherche',
  'refus',
  'repere',
  'reprendre',
  'scelle',
  'sos',
  'telephone',
  'vitrine',
  'voix',
  'zone',
] as const;
export type GrandTeintIconName = (typeof GRAND_TEINT_ICONS)[number];
