#!/usr/bin/env python3
"""WO-5.1 — the Grand Teint icon set → components, generated from the
design-reference SVGs so the output is reproducible byte-for-byte.
Emits: (a) an RN module (react-native-svg, currentColor via the Svg color
prop, default 20 dp) and (b) a PWA inline module (svg strings, currentColor
driven by CSS color). Zero interpretation — the geometry is copied verbatim.
"""
import sys, re, os
from xml.etree import ElementTree as ET

SRC_DIR, RN_OUT, PWA_OUT = sys.argv[1], sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else None
NS = "{http://www.w3.org/2000/svg}"
# Emit the SVG namespace as the DEFAULT (no ns0: prefix) when reserializing
# elements for the PWA inline path — otherwise ET.tostring stamps <ns0:path…>
# which no browser renders as SVG.
ET.register_namespace("", "http://www.w3.org/2000/svg")

def pascal(name):
    return "Icon" + "".join(p.capitalize() for p in re.split(r"[-_]", name))

CAMEL = {"stroke-width": "strokeWidth", "stroke-linecap": "strokeLinecap",
         "stroke-linejoin": "strokeLinejoin", "fill-rule": "fillRule",
         "clip-rule": "clipRule", "stroke-dasharray": "strokeDasharray"}

def rn_attrs(el):
    out = []
    for k, v in el.attrib.items():
        k = k.replace(NS, "")
        prop = CAMEL.get(k, k)
        out.append(f'{prop}="{v}"' if not re.fullmatch(r"-?[0-9.]+", v) else f'{prop}={{{v}}}')
    return " ".join(out)

RN_TAG = {"path": "Path", "circle": "Circle", "rect": "Rect"}

names = sorted(f[:-4] for f in os.listdir(SRC_DIR) if f.endswith(".svg"))
rn_parts, pwa_parts, pwa_names = [], [], []

for name in names:
    tree = ET.parse(os.path.join(SRC_DIR, f"{name}.svg"))
    root = tree.getroot()
    sw = root.attrib.get("stroke-width", "1.9")
    children_rn, children_svg = [], []
    for el in root:
        tag = el.tag.replace(NS, "")
        # RN element
        children_rn.append(f"      <{RN_TAG[tag]} {rn_attrs(el)} />")
        # raw svg element (for PWA inline) — reserialize verbatim
        raw = ET.tostring(el, encoding="unicode").replace(NS, "").strip()
        raw = re.sub(r'\s*/>', ' />', raw)
        children_svg.append(raw)
    comp = pascal(name)
    rn_parts.append(
        f"export function {comp}({{ size = 20, color = 'currentColor' }}: IconProps) {{\n"
        f"  return (\n"
        f'    <Svg width={{size}} height={{size}} viewBox="0 0 24 24" fill="none"\n'
        f'      stroke={{color}} strokeWidth={{{sw}}} strokeLinecap="round" strokeLinejoin="round"\n'
        f'      color={{color}} accessibilityRole="image">\n'
        + "\n".join(children_rn) + "\n"
        f"    </Svg>\n"
        f"  );\n"
        f"}}"
    )
    inner = "".join(children_svg)
    pwa_parts.append(
        f"  {name}: (size = 20) =>\n"
        f'    `<svg xmlns="http://www.w3.org/2000/svg" width="${{size}}" height="${{size}}" '
        f'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="{sw}" '
        f'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{inner}</svg>`,'
    )
    pwa_names.append(name)

rn_module = (
    "// GENERATED by scripts/gen-icons.py from design-reference/grand-teint/icons — DO NOT EDIT BY HAND.\n"
    "// WO-5.1 — the 26 Grand Teint glyphs as react-native-svg components. currentColor\n"
    "// resolves against the `color` prop; default 20 dp (legible at the design's icon size).\n"
    "import { Svg, Path, Circle, Rect } from 'react-native-svg';\n\n"
    "export interface IconProps {\n  /** dp; the design draws the set on a 24-unit grid, shown at 20 dp. */\n"
    "  size?: number;\n  /** any theme ink token; drives every stroke/fill via currentColor. */\n"
    "  color?: string;\n}\n\n"
    + "\n\n".join(rn_parts) + "\n\n"
    "export const GRAND_TEINT_ICONS = [\n"
    + ",\n".join(f"  '{n}'" for n in names) + ",\n] as const;\n"
    "export type GrandTeintIconName = (typeof GRAND_TEINT_ICONS)[number];\n"
)
os.makedirs(os.path.dirname(RN_OUT), exist_ok=True)
open(RN_OUT, "w").write(rn_module)
print(f"RN icons → {RN_OUT} ({len(names)} components)")

if PWA_OUT:
    pwa_module = (
        "// GENERATED by scripts/gen-icons.py from design-reference/grand-teint/icons — DO NOT EDIT BY HAND.\n"
        "// WO-5.1 — the 26 Grand Teint glyphs as inline SVG strings (PWA, zero deps).\n"
        "// currentColor is driven by the element's CSS `color`; size is a parameter.\n\n"
        "export const grandTeintIcon = {\n" + "\n".join(pwa_parts) + "\n} as const;\n\n"
        "export type GrandTeintIconName = keyof typeof grandTeintIcon;\n"
        "export const GRAND_TEINT_ICON_NAMES = Object.keys(grandTeintIcon) as GrandTeintIconName[];\n"
    )
    os.makedirs(os.path.dirname(PWA_OUT), exist_ok=True)
    open(PWA_OUT, "w").write(pwa_module)
    print(f"PWA icons → {PWA_OUT} ({len(pwa_names)} entries)")
